spring:
  data:
    mongodb:
      uri: mongodb://keshav-db-support:rfZ4MkHRTyUmDInei7xJ4rBfIOlZNLArdprU9c8zDyXzFwszp9l2uDzxw43T1vqovZtaJ4UGOclMp5vEux0BqA==@keshav-db-support.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
      database: keshav-db-support
      username: keshav-db-support
      password: rfZ4MkHRTyUmDInei7xJ4rBfIOlZNLArdprU9c8zDyXzFwszp9l2uDzxw43T1vqovZtaJ4UGOclMp5vEux0BqA==

azure:
  mongo:
    db-name: keshav-db-support
    host: keshav-db-support.documents.azure.com
    port: 10255
    uri: mongodb://keshav-db-support:rfZ4MkHRTyUmDInei7xJ4rBfIOlZNLArdprU9c8zDyXzFwszp9l2uDzxw43T1vqovZtaJ4UGOclMp5vEux0BqA==@keshav-db-support.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
    username: keshav-db-support
    password: rfZ4MkHRTyUmDInei7xJ4rBfIOlZNLArdprU9c8zDyXzFwszp9l2uDzxw43T1vqovZtaJ4UGOclMp5vEux0BqA==

